=begin comment

ProcessMaker API

This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.

OpenAPI spec version: 1.0.0
Contact: support@processmaker.io
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package ProcessMaker::PMIO::Object::UserAttributes;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

ProcessMaker API

This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.

OpenAPI spec version: 1.0.0
Contact: support@processmaker.io
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "ProcessMaker::PMIO::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'UserAttributes',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'username' => {
    	datatype => 'string',
    	base_name => 'username',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'password' => {
    	datatype => 'string',
    	base_name => 'password',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'firstname' => {
    	datatype => 'string',
    	base_name => 'firstname',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'lastname' => {
    	datatype => 'string',
    	base_name => 'lastname',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'email' => {
    	datatype => 'string',
    	base_name => 'email',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'expires_at' => {
    	datatype => 'string',
    	base_name => 'expires_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'status' => {
    	datatype => 'string',
    	base_name => 'status',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'country' => {
    	datatype => 'string',
    	base_name => 'country',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'city' => {
    	datatype => 'string',
    	base_name => 'city',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'location' => {
    	datatype => 'string',
    	base_name => 'location',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'address' => {
    	datatype => 'string',
    	base_name => 'address',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'phone' => {
    	datatype => 'string',
    	base_name => 'phone',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'fax' => {
    	datatype => 'string',
    	base_name => 'fax',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'cellular' => {
    	datatype => 'string',
    	base_name => 'cellular',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'zip_code' => {
    	datatype => 'string',
    	base_name => 'zip_code',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'position' => {
    	datatype => 'string',
    	base_name => 'position',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'resume' => {
    	datatype => 'string',
    	base_name => 'resume',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'birthday_at' => {
    	datatype => 'string',
    	base_name => 'birthday_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'bookmark_start_cases' => {
    	datatype => 'string',
    	base_name => 'bookmark_start_cases',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'time_zone' => {
    	datatype => 'string',
    	base_name => 'time_zone',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'default_lang' => {
    	datatype => 'string',
    	base_name => 'default_lang',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'created_at' => {
    	datatype => 'string',
    	base_name => 'created_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'updated_at' => {
    	datatype => 'string',
    	base_name => 'updated_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'clients' => {
    	datatype => 'ARRAY[int]',
    	base_name => 'clients',
    	description => '',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'username' => 'string',
    'password' => 'string',
    'firstname' => 'string',
    'lastname' => 'string',
    'email' => 'string',
    'expires_at' => 'string',
    'status' => 'string',
    'country' => 'string',
    'city' => 'string',
    'location' => 'string',
    'address' => 'string',
    'phone' => 'string',
    'fax' => 'string',
    'cellular' => 'string',
    'zip_code' => 'string',
    'position' => 'string',
    'resume' => 'string',
    'birthday_at' => 'string',
    'bookmark_start_cases' => 'string',
    'time_zone' => 'string',
    'default_lang' => 'string',
    'created_at' => 'string',
    'updated_at' => 'string',
    'clients' => 'ARRAY[int]'
} );

__PACKAGE__->attribute_map( {
    'username' => 'username',
    'password' => 'password',
    'firstname' => 'firstname',
    'lastname' => 'lastname',
    'email' => 'email',
    'expires_at' => 'expires_at',
    'status' => 'status',
    'country' => 'country',
    'city' => 'city',
    'location' => 'location',
    'address' => 'address',
    'phone' => 'phone',
    'fax' => 'fax',
    'cellular' => 'cellular',
    'zip_code' => 'zip_code',
    'position' => 'position',
    'resume' => 'resume',
    'birthday_at' => 'birthday_at',
    'bookmark_start_cases' => 'bookmark_start_cases',
    'time_zone' => 'time_zone',
    'default_lang' => 'default_lang',
    'created_at' => 'created_at',
    'updated_at' => 'updated_at',
    'clients' => 'clients'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
